<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>disasm</string>
	</array>
	<key>name</key>
	<string>Disasma</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>Section</string>
			<key>comment</key>
			<string>titolo di sezione</string>
			<key>end</key>
			<string>:</string>
			<key>name</key>
			<string>entity.name.function.disasm</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>registri</string>
			<key>match</key>
			<string>(eax|ax|ah|al|ebx|bx|bh|bl|ecx|cx|ch|cl|edx|dx|dh|dl|esp|sp|ebp|bp|esi|si|edi|di|cs|ds|ss|es|fs|gs|rax|rbx|rcx|rdx|rsi|rdi|rbp|rsp|rflags|rip)</string>
			<key>name</key>
			<string>keyword.commands.functional.disasm</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.disasm</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.disasm</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([0-9a-fA-F]{8})] ([^ ]*) +</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.disasm</string>
	<key>uuid</key>
	<string>1f7eca28-7c9b-48d5-92e9-987c5686d791</string>
</dict>
</plist>
